### ISSUE TITLE
Don't depend on react-dnd

### ISSUE THREAD

**Issue by cormacrelf** [redonkulus/react-dnd-touch-backend#96]
I'm the author of [angular-skyhook](https://github.com/cormacrelf/angular-skyhook), which is a re-implementation of `react-dnd` in Angular. It uses the same underlying `dnd-core` and is therefore compatible with all the backends.

The only problem is that existing backends tend to depend on `react-dnd`, and by extension, `react`. Technically, backends don't need any dependencies, but a `peerDependency` on `dnd-core` would be appropriate if you wanted to, and useful if it ever adds type annotations. Browsing this codebase, it seems like the only use of `react-dnd` is for the examples, which means the only work to do is change how the examples refer to the backend. You could probably just find and replace to make all references start with `../../` or something.

Similar issue, solved by splitting out react-specific parts (and a monorepo): https://github.com/LouisBrunner/dnd-multi-backend/issues/21

**Comment by longlho** [comment]
fixed

**Comment by cormacrelf** [comment]
For anyone wondering where: https://github.com/react-dnd/react-dnd/pull/1425/files#diff-b8b1ba0bbc674928b189df831f3c86b3
